### ISSUE TITLE
[ Falaê - IT TALENT ] - Ambiente de Desenvolvimento - Block ao atualizar a foto de perfil 

### ISSUE THREAD

**Issue by Lindemberg-Chagas** [falae-it-talent/falae#1]
Instalei a aplicação local e levei Block ao atualizar a foto de perfil 

![Screenshot_2](https://github.com/falae-it-talent/falae/assets/113239054/3c41c8b0-a8b7-4e7e-8cf7-c18555efd083)
Falta de permissão

**Comment by leandrohmanica** [comment]
Olá @Lindemberg-Chagas 
Criei um PR #2, pode revisar e testar se corrige o problema desta issue?

**Comment by lucasarags** [comment]
@Lindemberg-Chagas você tem noticias sobre a pr do leandro?

**Comment by moisesAlc** [comment]
@Lindemberg-Chagas , como ficou? Podemos fechar a issue?

**Comment by Lindemberg-Chagas** [comment]
@moisesAlc  pode fechar sim !
