### ISSUE TITLE
SISTEMA DO FALAE SE ENCONTRA FORA DO AR

### ISSUE THREAD

**Issue by NetoSiqueira** [falae-it-talent/falae#13]
No momento o sistema do falae se encontra fora do ar, impossibilitando fazer os testes
![Captura de tela 2023-11-13 084443](https://github.com/falae-it-talent/falae/assets/49129474/a18f9cf6-d12d-4587-906d-344ca4acb13c)

**Comment by lucasarags** [comment]
o Leandro relatou que não consegue nem acessar a instância, e vai averiguar com a infra o motivo de não esta no ar.

**Comment by moisesAlc** [comment]
Passando aqui para fechar as issues já resolvidas. Relativo a essa, passamos a utilizar a bastante tempo a instância http://34.203.52.95
