### ISSUE TITLE
[FALAE] IT TALENT- REGISTRO DE ISSUE (CENARIO DE TESTE - IMPORTAR PRANCHA COM ARQUIVO INCORRETO

### ISSUE THREAD

**Issue by NetoSiqueira** [falae-it-talent/falae#14]
Foi feito um teste nesse cenário seguindo essa sequência de passos:

- Dado que o usuario esteja na pagina sobre do site FALAE
- E o usuario está logado no sistema
- E o usuario clicar no link “Pranchas”
- Quando o usuario clicar no botao “Importar”
- E o usuario selecionar o arquivo incorreto
- E o usuario clicar no botao “Enviar”
- Entao o sistema deverá exibir uma mensagem informando que o arquivo está incorreto

![Captura de tela 2023-11-30 182639](https://github.com/falae-it-talent/falae/assets/49129474/f1659e6b-b38c-48e3-97cb-1ba7a29ea9ac)

![Captura de tela 2023-11-30 182702](https://github.com/falae-it-talent/falae/assets/49129474/fab73be0-18ad-4c25-89a2-1d2c3230d6af)

Onde o resultado desse teste mostra esse resultado

![Captura de tela 2023-11-30 182713](https://github.com/falae-it-talent/falae/assets/49129474/4cb8f8a8-323e-42f7-a78e-9bface7d737f)

Quando é feito essa importação de um arquivo que não seja correto, o sistema fica no modo de carregamento, que deixa o sistema inacessível, so podendo utilizar se de refresh.

**Comment by leandrohmanica** [comment]
@NetoSiqueira abri a #23 deve cobrir esta issue, por favor validar.

**Comment by NetoSiqueira** [comment]
Certo @leandrohmanica  pedir o pessoal do devop incorporar na instancia feita

**Comment by NetoSiqueira** [comment]
verificado e corrigido
