### ISSUE TITLE
[FALAE-AMBIENTE DE DESENVOLVIMENTO] IT TALENT- REGISTRO DE ISSUE (CENARIO DE TESTE - IMPORTAR PAGINA COM O ARQUIVO JA UTILIZADO

### ISSUE THREAD

**Issue by NetoSiqueira** [falae-it-talent/falae#19]
Foi feito um teste nesse cenário seguindo essa sequência de passos:

Dado que o usuario esteja na pagina sobre do site FALAE
 E o usuario está logado no sistema
 E o usuario clicar no link “Pranchas”
 E o usuario clicar na prancha
 Quando o usuario clicar no botao “Importar”  **[IMG 01]**
E o usuario selecionar o arquivo ja utilizado
 E o usuario clicar no botao “Enviar”  **[IMG 02]**
 Entao o sistema exibe uma mensagem: “ Não foi possível importar a pagina. A validação falhou: Nome já está em uso” 

**IMG 01**
![Captura de tela 2023-12-07 092021](https://github.com/falae-it-talent/falae/assets/49129474/6b432bb4-8ab0-493e-ad4c-5a39cd728a19)

**IMG 02**
![Captura de tela 2023-12-07 092032](https://github.com/falae-it-talent/falae/assets/49129474/2ee27eaf-7ab8-40b2-9374-b92fa1374c57)

Onde o resultado desse teste mostra esse resultado

![Captura de tela 2023-12-07 092043](https://github.com/falae-it-talent/falae/assets/49129474/b911d8f7-966e-46ac-8ad5-68061e0657ea)

Quando é feito essa importação de um arquivo que ja está em uso, o sistema fica no modo de carregamento, que deixa o sistema inacessível, so podendo utilizar se de refresh.

**Comment by leandrohmanica** [comment]
@NetoSiqueira abri a #23 deve cobrir esta issue, por favor validar.

**Comment by NetoSiqueira** [comment]
Verificado e corrigido
