### ISSUE TITLE
[FALAE] IT TALENT- REGISTRO DE ISSUE (CENARIO DE TESTE - ESQUECEU A SENHA COM EMAIL INVALIDO)

### ISSUE THREAD

**Issue by NetoSiqueira** [falae-it-talent/falae#6]
Foi feito um teste nesse cenário seguindo essa sequência de passos:

- Dado que o usuario esteja na pagina sobre do site FALAE
- E o usuario clicar no link "Entrar"
- E o usuario clicar no link "Esqueceu sua senha?"
- Quando o usuario preencher o campo email do esqueceu a senha com um email invalido
- E o usuario clicar no botao "Enviar"
- Entao o sistema exibe uma mensagem de erro: "Email e inválidos ou em branco ."

![Captura de tela 2023-10-21 123050](https://github.com/falae-it-talent/falae/assets/49129474/8c15d312-30b6-4ae9-97de-f2e3dc942700)

Onde o resultado desse teste mostra essa mensagem 

![Captura de tela 2023-10-21 123626](https://github.com/falae-it-talent/falae/assets/49129474/58165ee0-3f1c-4c35-9af3-65a9f772ba1f)

O resultado dessa mensagem mostrado no sistema subentende ao usuário que foi passado o email valido e que foi enviado para o email do mesmo, porem o sistema deveria emitir uma mensagem dizendo que esse email nao é valido ou que o campo se encontra em branco.

**Comment by leandrohmanica** [comment]
@NetoSiqueira PR aberta #8.

**Comment by NetoSiqueira** [comment]
![image](https://github.com/falae-it-talent/falae/assets/49129474/dfd3baa3-c8f7-498f-bb62-75bb216a4d95)

Feito teste e verificado que está de acordo com o ajuste. So acrescentaria a questão do email ficar em maiúsculo para ficar de acordo com as demais mensagem que tem no sistema. "Email inválido"
