### ISSUE TITLE
[FALAE] IT TALENT- REGISTRO DE ISSUE (CENARIO DE TESTE - ESQUECEU A SENHA COM EMAIL EM BRANCO)

### ISSUE THREAD

**Issue by NetoSiqueira** [falae-it-talent/falae#7]
Foi feito um teste nesse cenário seguindo essa sequência de passos:

- 	Dado que o usuario esteja na pagina sobre do site FALAE
- 	E o usuario clicar no link "Entrar"
- 	E o usuario clicar no link "Esqueceu sua senha?"
- 	Quando o usuario não preencher o campo email do esqueceu a senha
- 	E o usuario clicar no botao "Enviar"
- 	Entao o sistema exibe uma mensagem: "Email e inválidos ou em branco."

![Captura de tela 2023-10-21 134210](https://github.com/falae-it-talent/falae/assets/49129474/b858c216-b7f5-4da6-b987-ca48c7bcc02b)

Onde o resultado desse teste mostra essa mensagem

![Captura de tela 2023-10-21 123626](https://github.com/falae-it-talent/falae/assets/49129474/40ab6b52-a4c6-475e-96cb-acdb7218ac32)

O resultado dessa mensagem mostrado no sistema subentende ao usuário que foi passado o email valido e que foi enviado para o email do mesmo, porem o sistema deveria emitir uma mensagem dizendo que esse email nao é valido ou que o campo se encontra em branco.

**Comment by leandrohmanica** [comment]
@NetoSiqueira PR aberta #8.

**Comment by NetoSiqueira** [comment]
![image](https://github.com/falae-it-talent/falae/assets/49129474/bb219bd7-42ff-404c-aec8-62b1ea3619b3)
Feito teste e verificado que está de acordo com o ajuste. So acrescentaria a questão do email ficar em maiúsculo para ficar de acordo com as demais mensagem que tem no sistema. "Email inválido"

**Comment by leandrohmanica** [comment]
@NetoSiqueira embora a imagem aqui apareça letra minúscula, na PR está com letra maiúscula

![image](https://github.com/falae-it-talent/falae/assets/3502320/e71ef235-7d96-48ff-8c41-dbb76111d908)

Refereência: https://github.com/falae-it-talent/falae/pull/8/files#diff-00d777ed19791f38aacbcff5bc2f3b91ad0b591181a5332e29fcf3382b146e65R553.

**Comment by NetoSiqueira** [comment]
Entendi, obrigado @leandrohmanica
